version: "3"

vars:
  CONTAINER_NAME: webpack-2-mfp
  DOCKER_IMAGE: webpack-2-mfp

tasks:
  install-auth:
    dir: auth
    cmds: 
      - yarn install

  install-container:
    dir: container
    cmds:
      - yarn install

  install-dashboard:
    dir: dashboard
    cmds: 
      - yarn install

  install-marketing:
    dir: marketing
    cmds: 
      - yarn install

  install:
    cmds:
      - task: install-auth
      - task: install-container
      - task: install-dashboard
      - task: install-marketing
    
  start-auth:
    prefix: auth
    dir: auth
    cmds: 
      - yarn start

  start-container:
    prefix: container
    dir: container
    cmds: 
      - yarn start

  start-dashboard:
    prefix: dashboard
    dir: dashboard
    cmds:
      - yarn start

  start-marketing:
    prefix: marketing
    dir: marketing
    cmds:
      - yarn start

  build-auth:
    prefix: auth
    dir: auth
    cmds:
      - yarn build

  build-container:
    prefix: container
    dir: container
    cmds:
      - yarn build

  build-dashboard:
    prefix: dashboard
    dir: dashboard
    cmds:
      - yarn build

  build-marketing:
    prefix: marketing
    dir: marketing
    cmds:
      - yarn build

  build:
    deps: [build-auth, build-container, build-dashboard, build-marketing]

  docker-build-image:
    cmds:
      - docker build -t {{.DOCKER_IMAGE}} .
  
  docker-run:
    cmds:
      - docker run --rm -d -p 8000:80 --name {{.CONTAINER_NAME}} {{.DOCKER_IMAGE}}

  docker-stop:
    cmds:
      - docker stop {{.CONTAINER_NAME}}
